[main]
#font=FiraCode:size=10
font=Lato:size=10
lines=10
width=37
icons-enabled=yes
fuzzy=yes

[colors]
# Catppuccin Macchiato
background=24273aff      # Base
text=cad3f5ff            # Text
match=91d7e3ff           # Sky
selection=5b6078ff       # Surface2
selection-text=cad3f5ff  # Text
selection-match=91d7e3ff # Sky
border=91d7e3ff          # Sky

[border]
width=1
radius=10
